### ISSUE TITLE
Submitting files opened on another client fails

### ISSUE THREAD

**Issue by k-dovgan** [Samsung/Universum#193]
Originally created on Fri, 7 Sep 2018 11:53:54 +0300

```
[18:32:54][1. Executing] Traceback (most recent call last):
[18:32:54][1. Executing]   File "/usr/local/lib/python2.7/dist-packages/_universum/utils.py", line 147, in excepted_function
[18:32:54][1. Executing]     func(*args, **kwargs)
[18:32:54][1. Executing]   File "/usr/local/lib/python2.7/dist-packages/_universum/utils.py", line 170, in function_in_block
[18:32:54][1. Executing]     return self.structure.run_in_block(func, block_name, pass_errors, self, *args, **kwargs)
[18:32:54][1. Executing]   File "/usr/local/lib/python2.7/dist-packages/_universum/structure_handler.py", line 113, in run_in_block
[18:32:54][1. Executing]     result = operation(*args, **kwargs)
[18:32:54][1. Executing]   File "/usr/local/lib/python2.7/dist-packages/_universum/utils.py", line 92, in function_to_run
[18:32:54][1. Executing]     result = function(*args, **kwargs)
[18:32:54][1. Executing]   File "/usr/local/lib/python2.7/dist-packages/submit.py", line 54, in execute
[18:32:54][1. Executing]     edit_only=self.settings.edit_only)
[18:32:54][1. Executing]   File "/usr/local/lib/python2.7/dist-packages/_universum/vcs/perforce_vcs.py", line 207, in submit_new_change
[18:32:54][1. Executing]     if line["action"] == "add":
[18:32:54][1. Executing] TypeError: string indices must be integers, not str
```

**Comment by k-dovgan** [comment]
Originally posted by k.dovgan on Fri, 7 Sep 2018 11:55:47 +0300

This bug is caused by p4python returning list of reconciled files AND string info about files being opened on another client.
To prevent this from happening, info strings should be filtered.

**Comment by k-dovgan** [comment]
Resolved on Tue, 11 Sep 2018 14:24:25 +0300
