### ISSUE TITLE
universum_uncrustify doesn't read file-list

### ISSUE THREAD

**Issue by k-dovgan** [Samsung/Universum#212]
Originally created on Thu, 15 Nov 2018 10:09:54 +0200

`run_uncrustify = Variations([dict(name='Uncrustify check',code_report=True, directory=os.path.join(get_project_root()), command=["universum_uncrustify", "--file-list", "./tools/uncrustify.list", "--cfg-file", "./tools/uncrustify.cfg"])])`
```
$ /usr/local/bin/universum_uncrustify --file-list ./tools/uncrustify.list --cfg-file ./tools/uncrustify.cfg
stderr: Traceback (most recent call last):
stderr:   File "/usr/local/bin/universum_uncrustify", line 11, in <module>
stderr:     load_entry_point('Universum==0.16.0', 'console_scripts', 'universum_uncrustify')()
stderr:   File "/usr/local/lib/python2.7/dist-packages/analyzers/uncrustify.py", line 146, in main
stderr:     return analyze.execute()
stderr:   File "/usr/local/lib/python2.7/dist-packages/analyzers/uncrustify.py", line 72, in execute
stderr:     analyze_files = self.parse_files()
stderr:   File "/usr/local/lib/python2.7/dist-packages/analyzers/uncrustify.py", line 43, in parse_files
stderr:     with open(self.file_list) as f:
stderr: TypeError: coercing to Unicode: need string or buffer, list found
Module sh got exit code 1
```

**Comment by k-dovgan** [comment]
Resolved on Tue, 20 Nov 2018 15:50:39 +0200
