### ISSUE TITLE
Unexpected fail during the swarm review build

### ISSUE THREAD

**Issue by k-dovgan** [Samsung/Universum#213]
Originally created on Thu, 15 Nov 2018 17:11:32 +0200

Partial build log:
```
[13:24:45] :             [2. Finalizing] 2.3. Disconnecting
[13:24:45]W:             [2. Finalizing] 2.4. Cleaning copied sources
[13:24:45]W:                 [2.4. Cleaning copied sources] Traceback (most recent call last):
[13:24:45]W:                 [2.4. Cleaning copied sources]   File "/usr/local/lib/python2.7/dist-packages/_universum/lib/utils.py", line 168, in excepted_function
[13:24:45]W:                 [2.4. Cleaning copied sources]     func(*args, **kwargs)
[13:24:45]W:                 [2.4. Cleaning copied sources]   File "/usr/local/lib/python2.7/dist-packages/_universum/main.py", line 67, in execute
[13:24:45]W:             [2. Finalizing]     self.vcs.prepare_repository()
[13:24:45]W:         [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/_universum/lib/utils.py", line 191, in function_in_block
[13:24:45]W:         [Step 1/2]     return self.structure.run_in_block(func, block_name, pass_errors, self, *args, **kwargs)
[13:24:45]W:         [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/_universum/modules/structure_handler.py", line 115, in run_in_block
[13:24:45]W:         [Step 1/2]     result = operation(*args, **kwargs)
[13:24:45]W:         [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/_universum/modules/vcs/vcs.py", line 108, in prepare_repository
[13:24:45]W:         [Step 1/2]     self.driver.prepare_repository()
[13:24:45]W:         [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/_universum/modules/vcs/perforce_vcs.py", line 532, in prepare_repository
[13:24:45]W:         [Step 1/2]     self.diff()
[13:24:45]W:         [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/_universum/lib/utils.py", line 191, in function_in_block
[13:24:45]W:         [Step 1/2]     return self.structure.run_in_block(func, block_name, pass_errors, self, *args, **kwargs)
[13:24:45]W:         [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/_universum/modules/structure_handler.py", line 115, in run_in_block
[13:24:45]W:         [Step 1/2]     result = operation(*args, **kwargs)
[13:24:45]W:         [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/_universum/modules/vcs/perforce_vcs.py", line 465, in diff
[13:24:45]W:         [Step 1/2]     result = self.check_diff_for_depot(line)
[13:24:45]W:         [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/_universum/lib/utils.py", line 94, in function_to_run
[13:24:45]W:         [Step 1/2]     result = function(*args, **kwargs)
[13:24:45]W:         [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/_universum/modules/vcs/perforce_vcs.py", line 449, in check_diff_for_depot
[13:24:45]W:         [Step 1/2]     "diff", depot))
[13:24:45]W:         [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/_universum/lib/utils.py", line 128, in trim_and_convert_to_unicode
[13:24:45]W:         [Step 1/2]     line = unicode(line)
[13:24:45]W:         [Step 1/2]   File "/usr/local/lib/python2.7/dist-packages/sh.py", line 893, in _unicode_
[13:24:45]W:         [Step 1/2]     self.call_args["decode_errors"])
[13:24:45]W:         [Step 1/2] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4753: ordinal not in range(128)
[13:24:45]i:         [Step 1/2] ##teamcity[setParameter name='STOPPED_BY_USER' value='false']
[13:24:45]W:         [Step 1/2] Process exited with code 1
[13:24:45]E:         [Step 1/2] Process exited with code 1
[13:24:45]E:         [Step 1/2] Step Download and run (Command Line) failed
```

**Comment by k-dovgan** [comment]
Originally posted by k.dovgan on Thu, 15 Nov 2018 17:18:48 +0200

Anhelina Shevchuk, I believe this issue might be caused by "check_diff_for_depot" function. Please investigate and fix.

**Comment by k-dovgan** [comment]
Originally posted by an.shevchuk on Fri, 16 Nov 2018 15:59:38 +0200

Seems, that p4python diff tried to get diff between binaries (.so files that were changed) and line passed to `trim_and_convert_to_unicode()` a `bytearray("â")` or something like that, and should be processed like `line = line.decode("utf-8", "replace")` instead of `line = unicode(line)`.
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 4753: ordinal not in range(128)
00e2	â	0xE2	0xC3,0xA2	â	a circumflex
~/perforce/FIPS/ACVP $ grep -rn "â"
Binary file main/third-party/lib.so matches
```
But I'm sure that binaries don't need line-by-line comparison.
