### ISSUE TITLE
"'NoneType' object is not iterable" error during Swarm review build

### ISSUE THREAD

**Issue by k-dovgan** [Samsung/Universum#220]
Originally created on Fri, 30 Nov 2018 20:34:33 +0200

There is an error `'NoneType' object is not iterable` when you try to build with follow params together:
```
FAKE review id: REVIEW='123456789'
Changelist is real : SWARM_CHANGELIST='14897501'
FAKE pass/fail links: FAIL='test'; PASS='test'
```
Build log:
```
[20:28:01][1. Preparing repository] 1.1. Connecting
[20:28:01][1. Preparing repository] 1.2. Creating workspace +(1s)
[20:28:01][1.2. Creating workspace] 1.2.1. Checking that current and master CLs related change IDs are the same +(1s)
[20:28:02][1.2.1. Checking that current and master CLs related change IDs are the same] P4#run Warnings during command execution( "p4 describe 123456789" )
[20:28:02][1.2.1. Checking that current and master CLs related change IDs are the same]
[20:28:02][1.2.1. Checking that current and master CLs related change IDs are the same] [Warning]: '123456789 - no such changelist.'
[20:28:02][1.2.1. Checking that current and master CLs related change IDs are the same]
[20:28:02][1.2.1. Checking that current and master CLs related change IDs are the same]
[20:28:03][Step 1/2] <Checking that current and master CLs related change IDs are the same Failed>
[20:28:02][Step 1/2] 2. Finalizing
[20:28:02][2. Finalizing] 2.1. Connecting
[20:28:02][2. Finalizing] 2.2. Cleaning workspace
[20:28:03][2.2. Cleaning workspace] Traceback (most recent call last):
[20:28:03][2. Finalizing] File "/usr/local/lib/python2.7/dist-packages/_universum/lib/utils.py", line 168, in excepted_function
[20:28:03][2. Finalizing] func(*args, **kwargs)
[20:28:03][2. Finalizing] 2.3. Disconnecting
[20:28:03][2.3. Disconnecting] File "/usr/local/lib/python2.7/dist-packages/_universum/main.py", line 67, in execute
[20:28:03][2. Finalizing] self.vcs.prepare_repository()
[20:28:03][Step 1/2] File "/usr/local/lib/python2.7/dist-packages/_universum/lib/utils.py", line 191, in function_in_block
[20:28:03][Step 1/2] return self.structure.run_in_block(func, block_name, pass_errors, self, *args, **kwargs)
[20:28:03][Step 1/2] File "/usr/local/lib/python2.7/dist-packages/_universum/modules/structure_handler.py", line 115, in run_in_block
[20:28:03][Step 1/2] result = operation(*args, **kwargs)
[20:28:03][Step 1/2] File "/usr/local/lib/python2.7/dist-packages/_universum/modules/vcs/vcs.py", line 108, in prepare_repository
[20:28:03][Step 1/2] self.driver.prepare_repository()
[20:28:03][Step 1/2] File "/usr/local/lib/python2.7/dist-packages/_universum/modules/vcs/perforce_vcs.py", line 529, in prepare_repository
[20:28:03][Step 1/2] self.create_workspace()
[20:28:03][Step 1/2] File "/usr/local/lib/python2.7/dist-packages/_universum/lib/utils.py", line 191, in function_in_block
[20:28:03][Step 1/2] return self.structure.run_in_block(func, block_name, pass_errors, self, *args, **kwargs)
[20:28:03][Step 1/2] File "/usr/local/lib/python2.7/dist-packages/_universum/modules/structure_handler.py", line 115, in run_in_block
[20:28:03][Step 1/2] result = operation(*args, **kwargs)
[20:28:03][Step 1/2] File "/usr/local/lib/python2.7/dist-packages/_universum/lib/utils.py", line 94, in function_to_run
[20:28:03][Step 1/2] result = function(*args, **kwargs)
[20:28:03][Step 1/2] File "/usr/local/lib/python2.7/dist-packages/_universum/modules/vcs/perforce_vcs.py", line 358, in create_workspace
[20:28:03][Step 1/2] self.expand_workspace_parameters()
[20:28:03][Step 1/2] File "/usr/local/lib/python2.7/dist-packages/_universum/modules/vcs/perforce_vcs.py", line 342, in expand_workspace_parameters
[20:28:03][Step 1/2] cls.extend(swarm_cls)
[20:28:03][Step 1/2] TypeError: 'NoneType' object is not iterable
[20:28:03][Step 1/2] Process exited with code 1
[20:28:03][Step 1/2] Process exited with code 1
[20:28:03][Step 1/2] Step Download and run (Command Line) failed
```

**Comment by k-dovgan** [comment]
Resolved on Tue, 18 Dec 2018 17:55:44 +0200
