### ISSUE TITLE
Reporting build result Failed

### ISSUE THREAD

**Issue by a-osipov-toxa** [Samsung/Universum#473]
## Description

Step 'Reporting build result' failed with error **tuple index out of range**

## Steps to reproduce

List the performed steps, for example:
 * Request Swarm review. 
 * Note `SWARM_CHANGELIST` value for this (№1) revision
 * Update Swarm review (push new revision of any file)
 * Configure and run Universum with `SWARM_CHANGELIST` value from previous version of review

 * Command line: `python3.7 -u -m universum --no-diff --p4-client P4Workspace --p4-force-clean --report-build-start --report-build-success --report-to-review`

## Expected result

```
    7. Reporting build result
      ==> Here is the summarized build result:
....................................................................................................
      ==> Reporting successful build...
      ==> Swarm will be informed about build status by URL https://swarm.url/reviews/123456/tests/pass/AFC5C4CC-86D1A263762E.vXX/
    8. Finalizing
```

## Actual result

```
    7. Reporting build result
      ==> Here is the summarized build result:
....................................................................................................
      ==> Reporting successful build...
      ==> Swarm will be informed about build status by URL https://swarm.url/reviews/123456/tests/pass/AFC5C4CC-86D1A263762E.vXX/
      tuple index out of range
      <Reporting build result Failed>
```

## Environment

 - OS: Ubuntu 16.04.5
 - Python version 3.7
 - Universum version 0.18.7

## Additional context

If you change `pass_errors=False` -> `pass_errors=True`,
https://github.com/Samsung/Universum/blob/09ab9e596b01292a8b196a0cdb590cfb55571176/universum/modules/reporter.py#L96

You will get an error log:

```
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/universum/modules/vcs/swarm.py", line 193, in report_result
        six.moves.urllib.request.urlopen(link)
      File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python3.7/urllib/request.py", line 531, in open
        response = meth(req, response)
      File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python3.7/urllib/request.py", line 569, in error
        return self._call_chain(*args)
      File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: Forbidden
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/universum/lib/utils.py", line 178, in excepted_function
        func(*args, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/universum/main.py", line 83, in execute
        self.reporter.report_build_result()
      File "/usr/local/lib/python3.7/dist-packages/universum/lib/utils.py", line 201, in function_in_block
        return self.structure.run_in_block(func, block_name, pass_errors, self, *args, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/universum/modules/structure_handler.py", line 127, in run_in_block
        result = operation(*args, **kwargs)
      File "/usr/local/lib/python3.7/dist-packages/universum/modules/reporter.py", line 136, in report_build_result
        observer.report_result(is_successful, text, no_vote=self.settings.no_vote)
      File "/usr/local/lib/python3.7/dist-packages/universum/modules/vcs/swarm.py", line 198, in report_result
        if e.args[0] == "http error":
    IndexError: tuple index out of range
    Process exited with code 1
```

**Comment by k-dovgan** [comment]
Seems like this is the way Swarm decided to prohibit changing the status of not latest revisions: I tried to change a status for non-latest while being authorized, and it still returns error 403 (changing the latest status still works, though). Needs consideration.
