### ISSUE TITLE
Codec can't encode character

### ISSUE THREAD

**Issue by k-dovgan** [Samsung/Universum#483]
Universum ran in non-unicode environment:
```
$ locale
LANG=en_US
LANGUAGE=en_US:en
LC_CTYPE="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_COLLATE="en_US"
LC_MONETARY="en_US"
LC_MESSAGES="en_US"
LC_PAPER="en_US"
LC_NAME="en_US"
LC_ADDRESS="en_US"
LC_TELEPHONE="en_US"
LC_MEASUREMENT="en_US"
LC_IDENTIFICATION="en_US"
LC_ALL=
```
Results in following exception:
```
$ python3.7 -u -m universum --p4-client my_client --p4-force-clean  -lo file --no-archive --vcs-type p4 --artifact-dir artifacts1 --project-root temp_step_1
==> Universum 0.18.7 started execution
1. Preparing repository
 |   ==> Adding file <REPOSITORY_STATE.txt> to artifacts...
 |   1.1. Connecting
 |      |   1.1.1. Disconnecting
 |      |    |   2. Finalizing
 |   2.1. Connecting
 |      |   2.1.1. Disconnecting
 |      |    |    |   2.2. Cleaning workspace
 |      |   Error: [P4.run()] not connected.
 |      |   Error: [P4.run()] not connected.
 |    |   2.3. Disconnecting
 |   Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/universum/modules/structure_handler.py", line 127, in run_in_block
    result = operation(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/universum/lib/utils.py", line 120, in function_to_run
    result = function(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/universum/modules/vcs/perforce_vcs.py", line 92, in connect
    self.disconnect()
  File "/usr/local/lib/python3.7/dist-packages/universum/lib/utils.py", line 204, in function_in_block
    return self.structure.run_in_block(func, block_name, pass_errors, self, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/universum/modules/structure_handler.py", line 138, in run_in_block
    self.close_block()
  File "/usr/local/lib/python3.7/dist-packages/universum/modules/structure_handler.py", line 96, in close_block
    self.out.close_block(block.number, block.name, block.status)
  File "/usr/local/lib/python3.7/dist-packages/universum/modules/output/output.py", line 52, in close_block
    self.driver.close_block(number, name, status)
  File "/usr/local/lib/python3.7/dist-packages/universum/modules/output/terminal_based_output.py", line 55, in close_block
    stdout(self.block_level * "  ", " \u2514 ", Colors.green, "[Success]", Colors.reset)
  File "/usr/local/lib/python3.7/dist-packages/universum/modules/output/terminal_based_output.py", line 22, in stdout
    sys.stdout.write(''.join(args))
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2514' in position 5: ordinal not in range(256)
```
because `latin-1` cannot print `└ [Success]`

**Comment by i-keliukh** [comment]
Can we consider this a regression?
In any case, before fixing please implement test for this.
