### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte: invalid start byte

### ISSUE THREAD

**Issue by k-dovgan** [Samsung/Universum#584]
Encountered the following error:
```
23:26:38  |   1.5. Checking diff
23:26:40  |      └ [Success]
23:26:40  |   
23:26:40  └ [Success]
23:26:40 
23:26:40 2. Finalizing
23:26:40  |   2.1. Connecting
23:26:40  |   
23:26:40  |   2.2. Cleaning workspace
23:26:49  |   
23:26:49  |   2.3. Disconnecting
23:26:49  |   
23:26:49  |   2.4. Disconnecting
23:26:49  |   
23:26:49  |   2.5. Cleaning copied sources
23:26:49 Traceback (most recent call last):
23:26:49   File "/home/user/.local/lib/python3.7/site-packages/universum/lib/utils.py", line 165, in excepted_function
23:26:49     func(*args, **kwargs)
23:26:49   File "/home/user/.local/lib/python3.7/site-packages/universum/main.py", line 72, in execute
23:26:49     self.vcs.prepare_repository()
23:26:49   File "/home/user/.local/lib/python3.7/site-packages/universum/lib/utils.py", line 188, in function_in_block
23:26:49     return self.structure.run_in_block(func, block_name, pass_errors, self, *args, **kwargs)
23:26:49   File "/home/user/.local/lib/python3.7/site-packages/universum/modules/structure_handler.py", line 121, in run_in_block
23:26:49     result = operation(*args, **kwargs)
23:26:49   File "/home/user/.local/lib/python3.7/site-packages/universum/modules/vcs/vcs.py", line 173, in prepare_repository
23:26:49     self.driver.prepare_repository()
23:26:49   File "/home/user/.local/lib/python3.7/site-packages/universum/modules/vcs/perforce_vcs.py", line 564, in prepare_repository
23:26:49     self.diff()
23:26:49   File "/home/user/.local/lib/python3.7/site-packages/universum/lib/utils.py", line 188, in function_in_block
23:26:49     return self.structure.run_in_block(func, block_name, pass_errors, self, *args, **kwargs)
23:26:49   File "/home/user/.local/lib/python3.7/site-packages/universum/modules/structure_handler.py", line 121, in run_in_block
23:26:49     result = operation(*args, **kwargs)
23:26:49   File "/home/user/.local/lib/python3.7/site-packages/universum/modules/vcs/perforce_vcs.py", line 497, in diff
23:26:49     result: str = self.check_diff_for_depot(line)
23:26:49   File "/home/user/.local/lib/python3.7/site-packages/universum/lib/utils.py", line 104, in function_to_run
23:26:49     result = function(*args, **kwargs)
23:26:49   File "/home/user/.local/lib/python3.7/site-packages/universum/modules/vcs/perforce_vcs.py", line 466, in check_diff_for_depot
23:26:49     result: str = utils.trim_and_convert_to_unicode(diff_result.stdout)
23:26:49   File "/home/user/.local/lib/python3.7/site-packages/universum/lib/utils.py", line 119, in trim_and_convert_to_unicode
23:26:49     line = line.decode("utf-8")
23:26:49 UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 19771: invalid start byte
23:26:49  |      └ [Success]
```
Note no adding of REPOSITORY_DIFFERENCE.txt to artifacts.

Most likely, file diff contained non-UTF-8 characters.

**Comment by k-dovgan** [comment]
Better described in #614
